import { lazy } from "react";

const Container = lazy(() => import("../../common/Container"));
const ScrollToTop = lazy(() => import("../../common/ScrollToTop"));
const ContentBlock = lazy(() => import("../../components/ContentBlock"));

const Privacy = () => {
  const content = `
PRIVACY POLICY (ENGLISH)

SYSTEIN Solutions – Eenmanszaak
Last updated: [DATE]

1. Introduction
This Privacy Policy explains how SYSTEIN Solutions ("SYSTEIN", "we", "our", "us") processes personal data in connection with its AI-based products and services, including the AI coaching system "Coach Irene". SYSTEIN Solutions is a sole proprietorship (eenmanszaak) established in the Netherlands and complies with the EU General Data Protection Regulation (GDPR) and Dutch law.

2. Data Controller
SYSTEIN Solutions
De Lismortel 42 366
5612 AR Eindhoven
The Netherlands
Email: info@systein.nl
Website: www.systein.nl

3. Categories of Personal Data
We may process the following types of personal data:
– Identification and contact data (such as name and email address)
– Account and subscription data
– Information you provide via forms, email, or other communication channels
– Interaction data generated through the use of AI-based services such as Coach Irene
– Technical data such as IP address and access time in server logs

4. Purposes and Legal Bases
We process personal data for the following purposes:
– To provide and maintain our services, including AI-based coaching
– To manage subscriptions, billing, and payment administration
– To respond to questions and support requests
– To monitor system security and prevent abuse
– To comply with legal obligations

We rely on the following legal bases under the GDPR:
– Performance of a contract (Article 6(1)(b))
– Compliance with legal obligations (Article 6(1)(c))
– Legitimate interests (Article 6(1)(f)), including service security and improvement
– Consent (Article 6(1)(a)) where explicitly requested

5. Cookies and Tracking
We do not use cookies or similar tracking technologies for analytics or marketing. Our servers may register technical logs (such as IP address and timestamp) solely for security and diagnostic purposes.

6. Data Retention
We retain personal data only as long as necessary for the purposes described above or as required by applicable law. Where possible, AI interaction data is anonymised or pseudonymised. Financial and invoicing data may be retained for at least seven years to comply with Dutch tax regulations.

7. Data Sharing
We do not sell your personal data. We may share limited personal data with:
– Payment service providers for processing subscription payments
– Hosting and infrastructure providers that enable us to run our services
– Public authorities where required by law or court order

All processors are bound by written data processing agreements that comply with GDPR requirements.

8. International Transfers
Where personal data is transferred outside the European Economic Area (EEA), we implement appropriate safeguards, such as Standard Contractual Clauses or equivalent mechanisms required by EU law.

9. Your Rights
Under the GDPR, you have the following rights:
– Right of access to your personal data
– Right to rectification of inaccurate or incomplete data
– Right to erasure ("right to be forgotten") under certain conditions
– Right to restriction of processing
– Right to data portability
– Right to object to certain processing activities
– Right to withdraw consent at any time, where processing is based on consent

You may exercise these rights by contacting us at info@systein.nl. You also have the right to lodge a complaint with the Dutch Data Protection Authority (Autoriteit Persoonsgegevens).

10. AI-Specific Information
Coach Irene is an AI-based coaching tool and does not provide medical, psychological, therapeutic, or diagnostic services. Outputs generated by the AI may be incomplete, inaccurate, or inappropriate for your personal situation. You remain responsible for decisions made on the basis of AI outputs and should not use the service as a substitute for professional medical or psychological care.

11. Security Measures
We take reasonable technical and organisational measures to protect personal data against unauthorised access, loss, misuse, or alteration. However, no system can be guaranteed to be fully secure.

12. Changes to This Policy
We may update this Privacy Policy from time to time. The most recent version will always be available on our website. Continued use of our services after an update constitutes acceptance of the revised policy.

13. Contact
For questions, requests, or complaints regarding this Privacy Policy, please contact:
info@systein.nl


PRIVACYBELEID (NEDERLANDS)

SYSTEIN Solutions – Eenmanszaak
Laatst bijgewerkt: [DATUM]

1. Inleiding
In dit Privacybeleid wordt uitgelegd hoe SYSTEIN Solutions ("SYSTEIN", "wij", "ons") persoonsgegevens verwerkt in het kader van haar AI-diensten, waaronder het AI-coachsysteem "Coach Irene". SYSTEIN Solutions is een eenmanszaak gevestigd in Nederland en handelt in overeenstemming met de Algemene Verordening Gegevensbescherming (AVG) en de toepasselijke Nederlandse wetgeving.

2. Verwerkingsverantwoordelijke
SYSTEIN Solutions
De Lismortel 42 366
5612 AR Eindhoven
Nederland
E-mail: info@systein.nl
Website: www.systein.nl

3. Categorieën Persoonsgegevens
Wij kunnen onder meer de volgende persoonsgegevens verwerken:
– Naam, e-mailadres en andere contactgegevens
– Gegevens met betrekking tot abonnementen en betalingen
– Informatie die u verstrekt via formulieren, e-mail of andere communicatie
– Gegevens die voortkomen uit gebruik van AI-diensten zoals Coach Irene
– Technische gegevens zoals IP-adres en toegangsgegevens in serverlogs

4. Doeleinden en Rechtsgronden
Persoonsgegevens worden verwerkt voor:
– Het leveren en beheren van onze (AI-)diensten
– Abonnementsbeheer, facturatie en betalingsadministratie
– Klantenservice en beantwoording van vragen
– Beveiliging van systemen en het voorkomen van misbruik
– Naleving van wettelijke verplichtingen

Wij baseren ons op de volgende rechtsgronden:
– Uitvoering van een overeenkomst (art. 6 lid 1 sub b AVG)
– Wettelijke verplichting (art. 6 lid 1 sub c AVG)
– Gerechtvaardigd belang (art. 6 lid 1 sub f AVG)
– Toestemming (art. 6 lid 1 sub a AVG), indien expliciet gevraagd

5. Cookies en Tracking
Wij maken geen gebruik van cookies of vergelijkbare trackingtechnologieën voor analytics of marketingdoeleinden. Onze servers kunnen technische logs opslaan (zoals IP-adres en tijdstip) uitsluitend ten behoeve van beveiliging en foutdiagnose.

6. Bewaartermijnen
Persoonsgegevens worden niet langer bewaard dan noodzakelijk voor de in dit beleid beschreven doeleinden of zolang als wettelijk vereist. Gegevens voor financiële administratie kunnen ten minste zeven jaar worden bewaard. Waar mogelijk worden AI-interacties geanonimiseerd of gepseudonimiseerd.

7. Gegevensdeling
Wij verkopen uw persoonsgegevens niet. Gegevens kunnen worden gedeeld met:
– Betaaldienstverleners voor de verwerking van abonnementsgelden
– Hosting- en infrastructuurpartijen die onze diensten technisch mogelijk maken
– Overheidsinstanties indien wij hiertoe wettelijk verplicht zijn

Met alle verwerkers worden verwerkersovereenkomsten gesloten die voldoen aan de eisen van de AVG.

8. Doorgifte buiten de EER
Indien persoonsgegevens worden doorgegeven buiten de Europese Economische Ruimte (EER), treffen wij passende waarborgen zoals door de EU goedgekeurde modelcontractbepalingen.

9. Uw Rechten
U heeft onder de AVG onder meer recht op:
– Inzage in uw persoonsgegevens
– Rectificatie van onjuiste of onvolledige gegevens
– Verwijdering van gegevens onder bepaalde omstandigheden
– Beperking van de verwerking
– Overdraagbaarheid van gegevens
– Bezwaar tegen bepaalde verwerkingen
– Intrekking van toestemming (indien van toepassing)

U kunt uw rechten uitoefenen door contact met ons op te nemen via info@systein.nl. U heeft tevens het recht een klacht in te dienen bij de Autoriteit Persoonsgegevens.

10. AI-specifieke Informatie
Coach Irene is een AI-gebaseerd coachingshulpmiddel en biedt geen medisch, psychologisch, therapeutisch of diagnostisch advies. De gegenereerde AI-uitvoer kan onvolledig, onjuist of niet passend zijn voor uw situatie. U blijft zelf verantwoordelijk voor beslissingen die u op basis van deze uitvoer neemt en dient de dienst niet te gebruiken als vervanging voor professionele (medische of psychologische) hulp.

11. Beveiliging
Wij treffen passende technische en organisatorische maatregelen om persoonsgegevens te beschermen tegen onbevoegde toegang, verlies of misbruik. Geen enkel systeem kan echter absolute veiligheid garanderen.

12. Wijzigingen
Wij kunnen dit Privacybeleid van tijd tot tijd wijzigen. De meest recente versie is steeds beschikbaar op onze website. Voortgezet gebruik van onze diensten na wijziging houdt in dat u instemt met het gewijzigde beleid.

13. Contact
Voor vragen, verzoeken of klachten over dit Privacybeleid kunt u contact opnemen via:
info@systein.nl
  `;

  return (
    <Container>
      <ScrollToTop />
      <ContentBlock
        direction="left"
        title="Privacy Policy / Privacybeleid"
        content={content}
        icon="lock.svg"
        id="privacy-policy"
      />
    </Container>
  );
};

export default Privacy;